### PR TITLE
#Always use UTF-8 encoding when parsing DESCRIPTION files

### LINKED ISSUE #727: Encoding issue in package doc when accented name
I am using the latest (dev) version that I need because of the new MARC roles. When using the package-level doc, the accent in my name can't be rendered.

Steps

* `usethis::create_package("test")`

* modify "First" to "Maëlle"

```
Package: test
Version: 0.0.0.9000
Title: What the Package Does (One Line, Title Case)
Description: What the package does (one paragraph).
Authors@R: person("Maëlle", "Last", email = "first.last@example.com", role = c("aut", "cre"))
License: What license is it under?
Encoding: UTF-8
LazyData: true
ByteCompile: true
RoxygenNote: 6.0.1.9000

```

* `usethis::use_package_doc()`

* `roxygen2::roxygenise()`

Resulting test-package.Rd

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/test-package.R
\docType{package}
\name{test-package}
\alias{test}
\alias{test-package}
\title{test: What the Package Does (One Line, Title Case)}
\description{
What the package does (one paragraph).
}
\author{
\strong{Maintainer}: MaÃ«lle Last \email{first.last@example.com}

}
\keyword{internal}
````

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #727

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Well, ideally we should read it in the specified encoding, I think.

Actually, I think we could replace `read.dcf` with the desc package, we are already using it apparently. That (well, the dev version) handles encodings correctly AFAIR.

**Comment by jimhester** [comment]
Oh we are using desc? Then yes we should use it I will update this

**Comment by hadley** [comment]
Do you want to finish this off @jimhester?

**Comment by jimhester** [comment]
Ok I switched to using desc for this, however I am not sure if there needs to be additional changes as a result, the tests pass but there maybe some code paths that are untested which could fail.

**Comment by gaborcsardi** [comment]
And these as well?
https://github.com/klutometis/roxygen/blob/651a8db990213ae67b22f0de1b4d6cf74b0e0c5b/R/object-defaults.R#L32-L44

`desc::desc()` returns  an R6 object, not just a list, so it is not a drop in replacement.

**Comment by hadley** [comment]
Hmmm, maybe it's better to just fix the one `read.dcf()` call in roxygen2?  (And consider fuller desc usage at a later date)

**Comment by gaborcsardi** [comment]
Or just just fix the`read.desciption`call to create a list from the R6 object, and then the rest stays the  same.

**Comment by jimhester** [comment]
Ok I switched this to have `read.description()` just create a named list from the R6 object and we can handle a more thorough use of `desc` in the future.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
