### PR TITLE
@family refers to name only, not all aliases, #283

### PR DESCRIPTION
**Pull request by gaborcsardi**
I had this PR lying around. Details were discussed at #283. 

I am actually not convinced that this is always the good behavior. Sometimes it makes sense to link to all aliases, so if you have an idea on how to make this user configurable, per family, probably, I can update this PR.

### CODE REVIEW

**Comment by hadley** [comment]
Yeah, we need to think this one through

**Comment by hadley** [comment]
Could you please add a bullet to NEWS? I think I just need to try it out on a few of my projects and see how it feels.

**Comment by gaborcsardi** [comment]
OK, NEWS updated.

**Comment by hadley** [comment]
Thanks! I definitely prefer the new behaviour for roxygen2 itself

**Pull request merged**
