### PR TITLE
Added functionality to document R6classes using docblocks that allow …

### PR DESCRIPTION
**Pull request by hhoeflin**
Wanted to make a suggestion on how to document R6 classes.

It is mostly in its basic functionality copied from how roxygen handles rc classes, but expanded from there on how the documentation works.

In each R6class-method, it still uses docstrings for documentation, like RC classes. However, instead of a single string, it also accepts several of them - i.e. a docblock as several docstrings.

Inside the docblock, @param lines are allowed that specify parameters.

In the documentation, the methods are set as follows:

<method name>  *Usage:*
.... usage string of method ...

Description of method

If parameters were specified, this is followed by a 
*Parameters:*
\describe-block with one \item per parameter. 

It keeps the documentation for all methods together in a block and allows for more detail on how to document the parameters. usually, the documentation of each method will still be only 5 lines or so, so while it gets longer, it isn't excessively so.

### CODE REVIEW

**Comment by hhoeflin** [comment]
Documentation would look something like this

[trialr6.txt](https://github.com/klutometis/roxygen/files/210408/trialr6.txt)

and the resulting Rd file like this

[Myclass-class.txt](https://github.com/klutometis/roxygen/files/210409/Myclass-class.txt)

**Comment by dselivanov** [comment]
Why this can't be merged?

**Comment by epicfarmer** [comment]
This commit doesn't allow for \code or other similar commands inside the docstring.  Is there some reason its impossible to continue using the #' to denote roxygen comments?

**Comment by hadley** [comment]
Please discuss in #388

**Pull request closed without merging**
