### PR TITLE
Markdown, take 2

### PR DESCRIPTION
**Pull request by gaborcsardi**
From #431.

### CODE REVIEW

**Comment by hadley** [comment]
Should I merge this, and then work on the vignette in a separate pull?

**Comment by gaborcsardi** [comment]
Sure, why not?

**Comment by gaborcsardi** [comment]
Wait, need to fix a rebase typo. THanks Travis CI!

**Comment by gaborcsardi** [comment]
OK, should be good now.

**Comment by hadley** [comment]
Thanks!!

**Comment by njtierney** [comment]
This is exciting!

**Pull request merged**
