### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by krlmlr**
Translate some missing pieces from Markdown to Rd.

### CODE REVIEW

**Comment by hadley** [comment]
You didn't check in the R files?

**Comment by krlmlr** [comment]
I only reran document() using the current master of roxygen2. No changes to R files.

**Comment by gaborcsardi** [comment]
I think these might be leftover from the `stringr` mishap.

**Comment by krlmlr** [comment]
I'm getting the same results with stringr from CRAN and from GitHub.

**Comment by gaborcsardi** [comment]
@krlmlr You mean the "correct" result, yes, now you do. :)

See 4db98effad6f756c067aaea97c849e356c147d81 and 2249f1e0e3dfba8847311af9593d48a4b5671e46

**Comment by hadley** [comment]
Ah got it.

**Pull request merged**
