### PR TITLE
Parse in collate order

### PR DESCRIPTION
**Pull request by Geoff99**
Hi @hadley 
These changes should ensure that `roxygen2:::parse_package` reads the .R files in collate order when it parses them, and thus resolve issue #323 .
More than happy to make any improvements or corrections needed.

### CODE REVIEW

**Comment by Geoff99** [comment]
Hi @hadley 
Is there anything I need to do to finalise this pull request (so that roxygen2 *parses* documentation in collate order as well as *sources* it in collate order - see issue #323)?  It's been ready for review a while now.
Or is it just not time yet to consider minor changes to roxygen2.
Thanks
Geoff

**Comment by hadley** [comment]
I'll look at it when I'm next working on roxygen2

**Comment by krlmlr** [comment]
Looks good to me.

**Comment by hadley** [comment]
Could you please add a bullet to NEWS?

**Comment by Geoff99** [comment]
Bullet point about parse in collate order change has been added to NEWS.

**Comment by Geoff99** [comment]
NEWS entry moved to be under the top most bullet point. (Apologies, forgot to bring my local git copy up to date before adding NEWS entry in original location).

**Comment by hadley** [comment]
Thanks!

**Comment by Geoff99** [comment]
My pleasure :-)

**Pull request merged**
