### PR TITLE
Miscellanea around vignette roclet

### PR DESCRIPTION
**Pull request by krlmlr**
- Add vignette roclet to readme and to "roclet family" in docs
- Warn about unknown fields in `Roxygen` tag in `DESCRIPTION`

### CODE REVIEW

**Comment by hadley** [comment]
Looks like it broke a couple of tests?

**Comment by krlmlr** [comment]
Wasn't me, also happens in the current master ([link to build in my repo](https://travis-ci.org/krlmlr/roxygen/builds/64213081#L816)).

**Comment by krlmlr** [comment]
Possible reason: The last successful test ran two months ago under R 3.1.3 (https://travis-ci.org/klutometis/roxygen/builds/56471562#L697), some dependent packages might have changed too.

**Comment by krlmlr** [comment]
It's strange: `devtools::check()` works for me locally *and* in a `rocker/drd` based Docker container (`rwercker/base`, both R stable and R devel). I'm able to reproduce the error in an `ubuntu:precise` Docker container, will look further into the issue.

**Comment by krlmlr** [comment]
I'm collecting all my pull requests in my [develop branch](https://github.com/krlmlr/roxygen/tree/develop), merging this branch should close all pending pull requests (via the "Closes" entries in the commit messages).

**Comment by hadley** [comment]
Would you mind cleaning up these commits too? Then I'll merge

**Comment by krlmlr** [comment]
Cleaned.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
