### PR TITLE
Markdown: <...> -> \url{...}, not \href{...}{...}, fixes #500

### LINKED ISSUE #500: Markdown urls generate \href{} instead of \url{}
@gaborcsardi can you take a look please?  `<http://a.com>` generates `\href{http://a.com}{http://a.com}` instead of `\url{http://a.com}`

### PR DESCRIPTION
**Pull request by gaborcsardi**

### CODE REVIEW

**Comment by hadley** [comment]
Can you please redocument roxygen2 too?

**Comment by gaborcsardi** [comment]
Oh, sure, sorry, I did not realize you have already using markdown.... :)

**Comment by gaborcsardi** [comment]
Done.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
