### PR TITLE
Use more robust method to find DESCRIPTION when processing _PACKAGE sentinel

### LINKED ISSUE #439: _PACKAGE sentinel does not work with roxygenise()
...only with devtools::document().

```
> roxygen2::roxygenise()
Error in asNamespace(ns, base.OK = FALSE) : not a namespace
16: stop("not a namespace")
15: asNamespace(ns, base.OK = FALSE)
14: getNamespaceInfo(ns, "path")
13: file.path(getNamespaceInfo(ns, "path"), "DESCRIPTION")
12: read.dcf(file, keep.white = "Authors@R") at description.R#3
11: read.description(file.path(getNamespaceInfo(ns, "path"), "DESCRIPTION")) at object-from-call.R#41
10: find_data_for_package(env) at object-from-call.R#28
9: find_data(call, env) at object-from-call.R#6
8: object_from_call(call, env, preref) at parse.R#34
7: (function (call, ref, comment_ref) 
   {
     ...
6: mapply(FUN = f, ..., SIMPLIFY = FALSE)
5: Map(extract, parsed, refs, comment_refs) at parse.R#39
4: FUN(X[[i]], ...)
3: lapply(package_files(base_path), parse_file, env = env) at parse.R#3
2: parse_package(base_path, load_code) at roxygenize.R#59
1: roxygen2::roxygenise()
```

### PR DESCRIPTION
**Pull request by krlmlr**
so that it also works with roxygen2::roxygenise().

Fixes #439.

### CODE REVIEW

**Comment by hadley** [comment]
Can you please merge/rebase? 

(Or teach me how to do squash commits on the command line, preserving authorship)

**Comment by krlmlr** [comment]
Not sure how to do that via command line.

I have roughly the same feeling about squashed commits as you do about `theme_bw()`. I wish RStudio's Git client had a setting equivalent to the `--first-parent` switch to `git log` -- this would make squashing unnecessary, yet avoid cluttering the log.

**Comment by hadley** [comment]
Squashing PRs is nice because you don't have to worry about creating a "clean" PR, which is particularly handy for less experienced contributors.

**Comment by krlmlr** [comment]
There's a downside to squashed commits -- commits made on top of a PR can't be merged back easily to `master` anymore. This is important for me, but I have found workarounds by now.

**Pull request merged**
