### PR TITLE
Allow missing space before @include

### PR DESCRIPTION
**Pull request by krlmlr**
This is inconsistent, other tags allow a space before @, but @include doesn't.

Includes a test.

There is code duplication, the detection of a roxygen comment is also encoded in `LINE.DELIMITER` ([code ref](https://github.com/klutometis/roxygen/blob/cbd488066b7def0de00d679a076fbcaca94b74a0/R/parse-preref.R#L28)) but there the caret (start of text indicator) is missing. What to do about that?

### CODE REVIEW

**Comment by hadley** [comment]
Could you please squash and add a bullet to NEWS?

**Comment by krlmlr** [comment]
Resolved conflict, added bullet to NEWS.

**Comment by krlmlr** [comment]
Squashed, too.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
