### PR TITLE
Tidy filename Rd display from roxy_field_backref

### PR DESCRIPTION
**Pull request by LiNk-NY**
When multiple files are referenced in one documentation page, they will run off the page. 

This will create a one line per file format for the .Rd display. Example below:
```
cat(sprintf("%% Please edit in:\n%% %s\n",
      paste(c("a", "b", "c"), collapse = ",\n% ")))
```

### CODE REVIEW

**Comment by hadley** [comment]
I'd rather just wrap to (say) 80 characters

**Comment by LiNk-NY** [comment]
That works too

**Comment by hadley** [comment]
Do you want to have a go at implementing that?

**Comment by LiNk-NY** [comment]
Yes, should have it soon..

**Comment by LiNk-NY** [comment]
I didn't find an easy way to add "\n" to the output of `strwrap`. I ended up using paste twice. https://github.com/LiNk-NY/roxygen/blob/master/R/rd-tag-api.R#L97

**Comment by LiNk-NY** [comment]
Looks ready to go unless you have a more elegant way of adding "\n" to the end of a stri_wrap return

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
