### PR TITLE
Deduplicate aliases and fields in general

### LINKED ISSUE #586: Duplicated and reordered aliases
After an update, roxygen changed my Rd files in this way. it introduced aliases and deleted the trailing newline.

/edit: ah, i see the reordering is intentional. nevertheless, there’s something like the following missing somewhere:

```r
aliases <- setdiff(aliases, name)
# or at least
aliases <- unique(aliases)
````

What roxygen 6 did to my poor docs 😉:

```diff
--- man/extractions.Rd  (Revision 126592)
+++ man/extractions.Rd  (Arbeitskopie)
@@ -2,15 +2,22 @@
 % Please edit documentation in R/methods-extraction.r
 \docType{methods}
 \name{extractions}
+\alias{extractions}
+\alias{names.DPT}
+\alias{names,DPT-method}
 \alias{$,DPT-method}
+\alias{[[,DPT,character,missing-method}
+\alias{names.DiffusionMap}
+\alias{names,DiffusionMap-method}
 \alias{$,DiffusionMap-method}
-\alias{[[,DPT,character,missing-method}
 \alias{[[,DiffusionMap,character,missing-method}
 \alias{extractions}
-\alias{names,DPT-method}
-\alias{names,DiffusionMap-method}
-\alias{names.DPT}
-\alias{names.DiffusionMap}
+\alias{extractions}
+\alias{extractions}
+\alias{extractions}
+\alias{extractions}
+\alias{extractions}
+\alias{extractions}
 \title{Extraction methods}
 \usage{
 \S4method{names}{DiffusionMap}(x)
@@ -57,4 +64,3 @@
 \seealso{
 \link[base]{Extract}, \code{\link[base]{names}} for the generics. \link{DiffusionMap accessors}, \link{DiffusionMap methods}, \link{coercions} for more methods
 }
-
```

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #586

### CODE REVIEW

**Comment by flying-sheep** [comment]
hello?

**Comment by flying-sheep** [comment]
hi, sorry for being pushy, but i’d really like to have this in a release soon. could you please review it?

i always have to install my fork of roxygen at the moment to avoid #586.

**Comment by dmcglinn** [comment]
I would be excited to see this bug fix get merged.

**Comment by hadley** [comment]
Can you please add a bullet to NEWS?

**Comment by hadley** [comment]
@flying-sheep do you still want to finish this off? No problems if you can't; I can do it.

**Comment by flying-sheep** [comment]
hi, sorry for not responding, i was on vacation 😄

**Pull request merged**
