### PR TITLE
Never overwrite manually created NAMESPACE

### PR DESCRIPTION
**Pull request by krlmlr**
even when using roxygen2 for the first time.

A follow-up to #348, which works fine except for first-time usage of roxygen2.

### CODE REVIEW

**Comment by hadley** [comment]
Can you give a bit more detail about why this is the correct fix?

**Comment by krlmlr** [comment]
I feel `check` is a misnomer, 3124846 renames the argument so that the action is more explicit.

**Comment by hadley** [comment]
Should I rename `check` to `is_first`? The generic isn't exported (yet) so I think it's fine to change the argument name.

**Comment by krlmlr** [comment]
I'm updating the pull for the current codebase (to use is_first). I'm not entirely sure why the update behavior of roxygen2 should be any different for the first run.

**Comment by hadley** [comment]
Merged by hand in 596893c42b48aaa91781a60ffaad3c2dc0000ac0

**Pull request closed without merging**
