### PR TITLE
markdown code blocks escape percent signs

### PR DESCRIPTION
**Pull request by nteetor**
This problem was first raised in #699.

* My approach is based on that used for inline code
* I added one new test for code blocks and percent signs
* I updated the existing code blocks test to account for the escaped percent signs

### CODE REVIEW

**Comment by hadley** [comment]
Looks great!

Can you please add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by nteetor** [comment]
Sure thing

**Comment by hadley** [comment]
Can you please enable edit access for me? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by nteetor** [comment]
Sorry, didn't catch up to master. You're all set on editing.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
