### PR TITLE
fixed usage section for infix functions containing <-

### PR DESCRIPTION
**Pull request by nteetor**
A small change to the cases of `function_usage` in R/object-usage.R. Infix functions containing "<-" are no longer caught by the first if block. 

Added a test for infix functions containing "<-".

### CODE REVIEW

**Comment by hadley** [comment]
Could you please add a bullet to news too?

**Comment by nteetor** [comment]
I've added a bullet under the Other section.

**Comment by hadley** [comment]
Thanks! Will be releasing later today

**Comment by nteetor** [comment]
Yikes, cut that one a little close.

**Comment by hadley** [comment]
Doh, I forgot to pull so it won't be in until the next version :/

**Comment by nteetor** [comment]
Not a problem, I'll look forward to the next version.

**Pull request merged**
