### PR TITLE
Interpret `@evalRd` results as Markdown

### PR DESCRIPTION
**Pull request by krlmlr**
Do we want this? Happy to add a test.

### CODE REVIEW

**Comment by hadley** [comment]
Hmmmm, feels like that maybe should be a separate tag?

**Comment by krlmlr** [comment]
I considered that, but Markdown is currently opt-in anyway, so we should be on the safe side. I agree that the tag's name is misleading, though. Is it worth to add extra complexity here?

**Comment by gaborcsardi** [comment]
I don't know is this is needed, but I think that the patch is not correct, because it does not consider `@noMd` or the global `markdown` option.

**Comment by krlmlr** [comment]
I thought `full_markdown()` -> `markdown()` would look for that option by checking `markdown_on()` ?

**Comment by hadley** [comment]
I think the problem with making it unconditional is that the writer of the function (i.e. `@evalRd foo::bar()`) might be different to the package author (and hence doesn't know whether or not markdown will be enabled).

**Comment by gaborcsardi** [comment]
@krlmlr Yes, you are right, actually.

**Comment by krlmlr** [comment]
Closing for now, the user can use `@evalRd roxygen2:::full_markdown(...)` .

**Pull request closed without merging**
