### PR TITLE
Do not add extra newlines at the end of Rd files

### LINKED ISSUE #542: roxygen produces `.Rd` files with an extra newline
This causes an error if you have a check for trailing whitespace, e.g.

```shell
git diff --check cbbf8 5a4f96d

# ... rest of output omitted
man/default_data_format.Rd:20: new blank line at EOF.
man/load_options.Rd:16: new blank line at EOF.
```

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #542

### CODE REVIEW

**Comment by hadley** [comment]
Doesn't RStudio add them if you edit an Rd?

**Comment by jimhester** [comment]
I don't believe so...I did not edit any of the Rd files in this PR by hand, just re-ran `roxygenise()` on the package with the new code.

**Comment by hadley** [comment]
Can you double check? I thought a trailing nl was the usual standard

**Comment by gaborcsardi** [comment]
@hadley Trailing newlines are fine, but roxygen2 also adds an extra empty line, which is actually annoying. This is what Jim is trying to strip, right @jimhester ?

See the diff:
https://github.com/klutometis/roxygen/pull/543/files#diff-20c37c11964a952df8666363a284700aL20

**Comment by jimhester** [comment]
Yes exactly, all files should end in a newline, but roxygen was ending in
two.

**Comment by hadley** [comment]
Ok, got it.

**Pull request merged**
